<div class="jumbotron">
    <h1><a href="<?= $this->url('blog') ?>">Blog</a></h1>
    <p class="lead">Demo web application page.</p>
    <pre><?= __FILE__; ?></pre>
    <p><a class="btn btn-lg btn-success" href="<?= $this->url('blog/create', ['author' => 'owner', 'category' => 'oop']) ?>" role="button">Create Blog Action</a></p>
</div>

<h4>Variables</h4>
<?php

if (isset($args)) {
    var_dump($this->assigned());
}